### ISSUE TITLE
Sort on number of points instead of abbreviation

### ISSUE THREAD

**Issue by fekoch** [SilvanVerhoeven/vote-o-mat#3]
I noticed that the summary sorts the lists with their abbreviation. I assume this is a bug, as sorting by the number of points would be more user-friendly.

Additionally, for our use case at least, the order of the lists is of importance to our candidates and we should not re-order them without reason.

The sort happens here:

https://github.com/SilvanVerhoeven/vote-o-mat/blob/f0c95fd2887141302c2a7a630eef349de3421334/js/vote-o-mat.js#L449

In our instance we updated it to:

```javascript
results.sort(function (a, b) {return b[2] - a[2];})
```

This sorts by the number of points or keeps the original order, if equal.

**Comment by SilvanVerhoeven** [comment]
Thank you for noticing and providing a fix :)
